[functions.register]
verify_jwt = false

[functions.request-reset]
verify_jwt = false

[functions.verify-answers]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.change-username]
verify_jwt = true